### ISSUE TITLE
Setup site structure

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/lockedup-coders.github.io#1]
Setup the project structure and create a basic layout of a page that shows all team members.
Feel free to use frameworks like bootstrap.

ToDo
- [ ] Basic page with jumbotron
- [ ] sample team member listing component

**Comment by codebosss** [comment]
@YashKumarVerma I would like to work on this

**Comment by YashKumarVerma** [comment]
Closed in #4.
