### ISSUE TITLE
The HTML is not flexible.

### ISSUE THREAD

**Issue by KarandeepSinghCoder** [LockedUp-Coders/lockedup-coders.github.io#19]
Please get a reference from the below-given code to understand how it should be.

- [ ] Try understanding the use of flex-wrap and how it will help to make the site responsive.

> <div class="row text-center" style="display: flex; flex-wrap: wrap;">
         <div class="row text-center" style="display: flex; flex-wrap: wrap;">

            <div class="col-md-3 col-sm-6">
                <div class="thumbnail">
                        <img src="**/address**" alt="">
                        <div class="caption">
                                <h4> **name** </h4>
                        </div>  
                        <p>
                            **Other informations if required any **
                        </p>   
                </div>
            </div>
    </div>
</div>

![Screenshot (60)](https://user-images.githubusercontent.com/50829119/84354373-642d4800-abde-11ea-8324-1dcb6934175c.png)

in the above image, we can see every element is hardcoded into the HTML in 3 rows. 
We need to use one row with flexible thumbnail elements.

**Comment by YashKumarVerma** [comment]
something like flex ?

**Comment by hayat-tamboli** [comment]
please review this 

HTML
```
<div class="flexbox">
	<div class="d-flex flex-column justify-content-center align-items-center"><img width="150" height="150" src="https://picsum.photos/150?random=2" /><p>Person1</p></div>
	<div class="d-flex flex-column justify-content-center align-items-center"><img width="150" height="150" src="https://picsum.photos/150?random=3" /><p>Person2</p></div>
	<div class="d-flex flex-column justify-content-center align-items-center"><img width="150" height="150" src="https://picsum.photos/150?random=1" /><p>Person3</p></div>
</div>
```

CSS

```
.flexbox{
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
	align-items: center;
}
.flexbox div{
	margin: 1rem;
}
```
![image](https://user-images.githubusercontent.com/55529269/84435217-1270d600-ac4f-11ea-8dd1-50d85588fdde.png)
//it is still responsive and everything is in one division
please tell me if the issue is solved😀

**Comment by YashKumarVerma** [comment]
@hayat-tamboli send a pr.
