### ISSUE TITLE
Some profile images Very Heavy

### ISSUE THREAD

**Issue by vipul1999** [LockedUp-Coders/lockedup-coders.github.io#42]
Images added by some participants are up to 3MB which causes an **increase in the size** of the repo unnecessary.

![images is way too big it is taking space in the repo](https://user-images.githubusercontent.com/42087486/84565841-c8d8d600-ad89-11ea-8e2d-b7578110a38e.PNG)

**Comment by YashKumarVerma** [comment]
Todo
- [ ] Resize all images to 400x400px.

**Comment by tanay13** [comment]
i will do it

**Comment by YashKumarVerma** [comment]
There's still one profile which does not have it's image linked property (check broken image in live preview), fix it please .

**Comment by tanay13** [comment]
okay i will do that
