### ISSUE TITLE
Copy issue, PR tempalte from /meta

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/lockedup-coders.github.io#5]
Copy the issue and PR template from the meta-repository to this repository.

**Comment by vivekshah1801** [comment]
@YashKumarVerma may I know why this issue is reopened?
I already made the PR and it was merged as well.

**Comment by YashKumarVerma** [comment]
@vivekshah1801  your PR added the files to the root directory, and was therefore reverted. Send again.

**Comment by karankartikeya** [comment]
> @vivekshah1801 your PR added the files to the root directory, and was therefore reverted. Send again.

where are the files to be placed in this repository?
in the assets?

**Comment by YashKumarVerma** [comment]
.github as was done in /meta repository.

**Comment by YashKumarVerma** [comment]
Issue templates still missing here :cry:

**Comment by adinalini** [comment]
Can I add additions to this pull request? Or will I have to open a separate one

**Comment by vivekshah1801** [comment]
Solved this issue.
PR #48
