### ISSUE TITLE
Move images folder to assets

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/lockedup-coders.github.io#6]
1. All static assets need to be in the assets folder.
2. Delete images as they are not being used

**Comment by vivekshah1801** [comment]
I want to do this

**Comment by dhairyaostwal** [comment]
@YashKumarVerma recently pushed a PR regarding this. Kindly address the comments too.

**Comment by YashKumarVerma** [comment]
@vivekshah1801  if I've not explicitly mentioned to claim it, feel free to send a PR directly. Just mention the issue number while sending the PR. this will help us track them easily.
