### ISSUE TITLE
Remove .gitkeep

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/lockedup-coders.github.io#7]
- Remove the file as it is not needed.

To claim, read up, and comment on why it is not needed.

**Comment by vivekshah1801** [comment]
.gitkeep file is not the standard git norm. it is a dummy placeholder so git can remember your directory.

The reason, why some people put this .gitkeep file, is to make the empty directory trackable.
Git by default doesn't track empty directories.
So by putting .gitkeep file, we are making our empty directory "seem" non-empty and in turn, allow git to track that directory.

## What will happen if we don't have .gitkeep file?
if we don't have .gitkeep file, git will not track it and that directory will not be there in our commit and our remotes. so anyone who is pulling our code will not get that directory.

### for example
if I have an empty directory called "images" with no files in it. when I commit and push my code, that "images" folder will not be there on Github.


## Why we should delete this .gitkeep file now?
As we have "team.css" the directory "assets" is not empty.
Hence git will now track it, no need for any .gitkeep hacks!

**Comment by YashKumarVerma** [comment]
> .gitkeep file is not the standard git norm. it is a dummy placeholder so git can remember your directory.
> 
> The reason, why some people put this .gitkeep file, is to make the empty directory trackable.
> Git by default doesn't track empty directories.
> So by putting .gitkeep file, we are making our empty directory "seem" non-empty and in turn, allow git to track that directory.
> 
> ## What will happen if we don't have .gitkeep file?
> if we don't have .gitkeep file, git will not track it and that directory will not be there in our commit and our remotes. so anyone who is pulling our code will not get that directory.
> 
> ### for example
> if I have an empty directory called "images" with no files in it. when I commit and push my code, that "images" folder will not be there on Github.
> 
> ## Why we should delete this .gitkeep file now?
> As we have "team.css" the directory "assets" is not empty.
> Hence git will now track it, no need for any .gitkeep hacks!

whoa ! such a detailed reply. Really appreciated. :+1:  This would be surely helpful for someone who needs to know more about it. 


from now on, please give short points / the overview and that's enough. Being a hater of theory, won't ask you all to write answers :laughing:
