### ISSUE TITLE
Show team members from teams.json

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/lockedup-coders.github.io#8]
Currently, the site is static, add a feature to show details of team members from the .json file.

Claim it by stating the reasons for:
- why we are loading data from the .json file and not hard writing HTML ?? 
- how would you do it?

**Comment by KarandeepSinghCoder** [comment]
the data could be manipulated, saved, and displayed on the page using JavaScript, which makes the future changes really flexible. 

I would Like to claim it.
I will import data from the JSON file.
count the number of Team members using length().
Run a for loop to display the details of each member using ejs files 



> Embedded Javascript Templating is a templating engine used by Node.js. Template engine helps to create an HTML template with minimal code. Also, it can inject data into HTML template at the client-side and produce the final HTML. EJS is a simple templating language which is used to generate HTML markup with plain JavaScript. It also helps to embed JavaScript to HTML

**Comment by YashKumarVerma** [comment]
> the data could be manipulated, saved, and displayed on the page using JavaScript, which makes the future changes really flexible.
> 
> I would Like to claim it.
> I will import data from the JSON file.
> count the number of Team members using length().
> Run a for loop to display the details of each member using ejs files
> 
> > Embedded Javascript Templating is a templating engine used by Node.js. Template engine helps to create an HTML template with minimal code. Also, it can inject data into HTML template at the client-side and produce the final HTML. EJS is a simple templating language which is used to generate HTML markup with plain JavaScript. It also helps to embed JavaScript to HTML

cool @KarandeepSinghCoder .

but a bit from my side. we're not using a template engine here :eyes: 

waiting for your PR.

**Comment by YashKumarVerma** [comment]
Open to anyone

**Comment by PrachiSinghal86** [comment]
We use json file to load data on the website so that the changes can be reflected automatically and this reduces the load to update the details manually.
We can first load the json file in the html page and then with the help of the loop can traverse through the whole file and as the data will be stored in a proper structure we can display them according to the properties on the website.

**Comment by winay05** [comment]
Hi @KarandeepSinghCoder @YashKumarVerma, do we want the details to be displayed in like small elements for each user? is that it? cause I think that could be done using JQuery.

**Comment by vivekshah1801** [comment]
@PrachiSinghal86 @winay05 are you working on this issue?

if yes, keep working.
else I can take it up.

**Comment by winay05** [comment]
@vivekshah1801 go ahead.

**Comment by YashKumarVerma** [comment]
Anyone of you send PR. @PrachiSinghal86  or @vivekshah1801 
Just read data from the son file, loop through it, and show user image and details. Some code is already there in HTML if you check.

**Comment by codebosss** [comment]
Guys, I guess this styling would look good
-displaying details while hovering on the image
![Capture](https://user-images.githubusercontent.com/53134103/84468767-3c50e980-ac9d-11ea-86d7-400ef6c68d4b.PNG)

**Comment by YashKumarVerma** [comment]
> Guys, I guess this styling would look good
> -displaying details while hovering on the image
> ![Capture](https://user-images.githubusercontent.com/53134103/84468767-3c50e980-ac9d-11ea-86d7-400ef6c68d4b.PNG)

Please don't put a color yet. Just keep the default bootstrap styling of a card.

**Comment by YashKumarVerma** [comment]
Still no PR for this ?
