### ISSUE TITLE
Make team listing responsive

### ISSUE THREAD

**Issue by KarandeepSinghCoder** [LockedUp-Coders/lockedup-coders.github.io#9]
When the window size is shrunk the number of images in each row remains the same.
Use  `<div class="col-md-3 col-sm-6">` to make it responsive.
when the window size decreases then the images per row should become 4 and for mid-size window let it be 4 images per row.

**Comment by codebosss** [comment]
Proposed a pull request regarding this.Thank You.

**Comment by dhairyaostwal** [comment]
@KarandeepSinghCoder @codebosss 

Hey guys good going with the website work! I would like to suggest if we could `border-radius` around photographs of team members. 

Thanks.

**Comment by dhairyaostwal** [comment]
> When the window size is shrunk the number of images in each row remains the same.
> Use `<div class="col-md-3 col-sm-6">` to make it responsive.
> when the window size decreases then the images per row should become 4 and for mid-size window let it be 4 images per row.

@KarandeepSinghCoder I tried using margin tag for making the photographs area responsive but it wasn't successful. Could you suggest something?
